// <auto-generated />
using System;
using Dji.Cloud.Infrastructure.MsSql.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dji.Cloud.Infrastructure.MsSql.Migrations
{
    [DbContext(typeof(DjiDbContext))]
    partial class DjiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.DeviceDictionaryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DeviceDesc");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("DeviceName");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int")
                        .HasColumnName("DeviceType");

                    b.Property<int>("Domain")
                        .HasColumnType("int")
                        .HasColumnName("Domain");

                    b.Property<int>("SubType")
                        .HasColumnType("int")
                        .HasColumnName("SubType");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("DeviceDictionaries", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.DeviceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("BoundStatus")
                        .HasColumnType("bit")
                        .HasColumnName("BoundStatus");

                    b.Property<long>("BoundTime")
                        .HasColumnType("bigint")
                        .HasColumnName("BoundTime");

                    b.Property<string>("ChildSerialNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ChildSerialNumber");

                    b.Property<bool>("CompatibleStatus")
                        .HasColumnType("bit")
                        .HasColumnName("CompatibleStatus");

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("DeviceDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DeviceDesc");

                    b.Property<string>("DeviceIndex")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("DeviceIndex");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("DeviceName");

                    b.Property<string>("DeviceSerialNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("DeviceSerialNumber");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int")
                        .HasColumnName("DeviceType");

                    b.Property<int>("Domain")
                        .HasColumnType("int")
                        .HasColumnName("Domain");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("FirmwareVersion");

                    b.Property<long>("LoginTime")
                        .HasColumnType("bigint")
                        .HasColumnName("LoginTime");

                    b.Property<string>("Nickname")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Nickname");

                    b.Property<int>("SubType")
                        .HasColumnType("int")
                        .HasColumnName("SubType");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UrlNormal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UrlNormal");

                    b.Property<string>("UrlSelect")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UrlSelect");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("UserId");

                    b.Property<int>("Version")
                        .HasMaxLength(32)
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Devices", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.DeviceFirmwareEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileMd5")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("FileMd5");

                    b.Property<string>("FileName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("FileName");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("FileSize");

                    b.Property<string>("FirmwareId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("FirmwareId");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("FirmwareVersion");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ObjectKey");

                    b.Property<long>("ReleaseDate")
                        .HasColumnType("bigint")
                        .HasColumnName("ReleaseDate");

                    b.Property<string>("ReleaseNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ReleaseNote");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("UserName");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("DeviceFirmwares", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.DeviceHmsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bid")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Bid");

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("HmsId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("HmsId");

                    b.Property<string>("HmsKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("HmsKey");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<string>("MessageEn")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MessageEn");

                    b.Property<string>("MessageZh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MessageZh");

                    b.Property<int>("Module")
                        .HasColumnType("int")
                        .HasColumnName("Module");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Tid")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Tid");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("DeviceHmses", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.DeviceLogsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("DeviceSerialNumber")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DeviceSerialNumber");

                    b.Property<long>("HappenTime")
                        .HasColumnType("bigint")
                        .HasColumnName("HappenTime");

                    b.Property<string>("LogsId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("LogsId");

                    b.Property<string>("LogsInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("LogsInfo");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UserName");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("DeviceLogs", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.DevicePayloadEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("DeviceSerialNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("DeviceSerialNumber");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("FirmwareVersion");

                    b.Property<string>("PayloadDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PayloadDesc");

                    b.Property<int>("PayloadIndex")
                        .HasColumnType("int")
                        .HasColumnName("PayloadIndex");

                    b.Property<string>("PayloadName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("PayloadName");

                    b.Property<string>("PayloadSerialNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("PayloadSerialNumber");

                    b.Property<int>("PayloadType")
                        .HasColumnType("int")
                        .HasColumnName("PayloadType");

                    b.Property<int>("SubType")
                        .HasColumnType("int")
                        .HasColumnName("SubType");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("DevicePayloads", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.FirmwareModelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("DeviceName");

                    b.Property<string>("FirmwareId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("FirmwareId");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("FirmwareModels", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.LogsFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("DeviceSerialNumber")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DeviceSerialNumber");

                    b.Property<string>("FileId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("FileId");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Fingerprint");

                    b.Property<string>("LogsId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("LogsId");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ObjectKey");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("Size");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("LogsFiles", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.LogsFileIndexEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BootIndex")
                        .HasColumnType("int")
                        .HasColumnName("BootIndex");

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("DeviceSerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("DeviceSerialNumber");

                    b.Property<int>("Domain")
                        .HasColumnType("int")
                        .HasColumnName("Domain");

                    b.Property<long>("EndTime")
                        .HasColumnType("bigint")
                        .HasColumnName("EndTime");

                    b.Property<string>("FileId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("FileId");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("Size");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint")
                        .HasColumnName("StartTime");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("LogsFileIndexes", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("MqttPassword")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("MqttPassword");

                    b.Property<string>("MqttUserName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("MqttUserName");

                    b.Property<string>("Password")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Password");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("UserId");

                    b.Property<string>("UserName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("UserName");

                    b.Property<int>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("UserType");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Manage.WorkspaceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BindCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("BindCode");

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("PlatformName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("PlatformName");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("WorkspaceDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("WorkspaceDesc");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("WorkspaceId");

                    b.Property<string>("WorkspaceName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("WorkspaceName");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Workspaces", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Map.ElementCoordinateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Altitude")
                        .HasPrecision(17, 14)
                        .HasColumnType("decimal(17,14)")
                        .HasColumnName("Altitude");

                    b.Property<string>("ElementId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ElementId");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(17, 14)
                        .HasColumnType("decimal(17,14)")
                        .HasColumnName("Latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(18, 14)
                        .HasColumnType("decimal(18,14)")
                        .HasColumnName("Longitude");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("ElementCoordinates", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Map.GroupElementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ClampToGround")
                        .HasColumnType("bit")
                        .HasColumnName("ClampToGround");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Color");

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<int>("Display")
                        .HasColumnType("int")
                        .HasColumnName("Display");

                    b.Property<string>("ElementId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ElementId");

                    b.Property<string>("ElementName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ElementName");

                    b.Property<int>("ElementType")
                        .HasColumnType("int")
                        .HasColumnName("ElementType");

                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("GroupId");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("UserName");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("GroupElements", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Map.GroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("GroupId");

                    b.Property<string>("GroupName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("GroupName");

                    b.Property<int>("GroupType")
                        .HasColumnType("int")
                        .HasColumnName("GroupType");

                    b.Property<bool>("IsDistributed")
                        .HasColumnType("bit")
                        .HasColumnName("IsDistributed");

                    b.Property<bool>("IsLock")
                        .HasColumnType("bit")
                        .HasColumnName("IsLock");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Groups", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Media.MediaFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("Drone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Drone");

                    b.Property<string>("FileId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("FileId");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FileName");

                    b.Property<string>("FilePath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FilePath");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Fingerprint");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("bit")
                        .HasColumnName("IsOriginal");

                    b.Property<string>("JobId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("JobId");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ObjectKey");

                    b.Property<string>("Payload")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Payload");

                    b.Property<int>("SubFileType")
                        .HasColumnType("int")
                        .HasColumnName("SubFileType");

                    b.Property<string>("TinnyFingerprint")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TinnyFingerprint");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("MediaFiles", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Wayline.WaylineFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("DroneModelKey")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("DroneModelKey");

                    b.Property<bool>("Favorited")
                        .HasColumnType("bit")
                        .HasColumnName("Favorited");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ObjectKey");

                    b.Property<string>("PayloadModelKeys")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PayloadModelKeys");

                    b.Property<string>("Sign")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Sign");

                    b.Property<string>("TemplateTypes")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("TemplateTypes");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("UserName");

                    b.Property<string>("WaylineId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("WaylineId");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("WaylineFiles", "dbo");
                });

            modelBuilder.Entity("Dji.Cloud.Infrastructure.Abstracts.Entities.Wayline.WaylineJobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BeginTime")
                        .HasColumnType("bigint")
                        .HasColumnName("BeginTime");

                    b.Property<long>("CompletedTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CompletedTime");

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("CreateTime");

                    b.Property<string>("DockSerialNumber")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DockSerialNumber");

                    b.Property<long>("EndTime")
                        .HasColumnType("bigint")
                        .HasColumnName("EndTime");

                    b.Property<int>("ErrorCode")
                        .HasColumnType("int")
                        .HasColumnName("ErrorCode");

                    b.Property<long>("ExecuteTime")
                        .HasColumnType("bigint")
                        .HasColumnName("ExecuteTime");

                    b.Property<string>("FileId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("FileId");

                    b.Property<string>("JobId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("JobId");

                    b.Property<int>("MediaCount")
                        .HasColumnType("int")
                        .HasColumnName("MediaCount");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.Property<int>("OutOfControlAction")
                        .HasColumnType("int")
                        .HasColumnName("OutOfControlAction");

                    b.Property<string>("ParentId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ParentId");

                    b.Property<int>("RthAltitude")
                        .HasColumnType("int")
                        .HasColumnName("RthAltitude");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("TaskType")
                        .HasColumnType("int")
                        .HasColumnName("TaskType");

                    b.Property<long?>("UpdateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdateTime");

                    b.Property<string>("UserName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("UserName");

                    b.Property<int>("WaylineType")
                        .HasColumnType("int")
                        .HasColumnName("WaylineType");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("WaylineJobs", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
